package clanavard.db.models.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _Config was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
@SuppressWarnings("deprecation")
public abstract class _Config extends BaseDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> BIRTHDAY_CHANNEL = Property.create("birthdayChannel", String.class);
    public static final Property<String> GUILD_ID = Property.create("guildId", String.class);

    protected String birthdayChannel;
    protected String guildId;


    public void setBirthdayChannel(String birthdayChannel) {
        beforePropertyWrite("birthdayChannel", this.birthdayChannel, birthdayChannel);
        this.birthdayChannel = birthdayChannel;
    }

    public String getBirthdayChannel() {
        beforePropertyRead("birthdayChannel");
        return this.birthdayChannel;
    }

    public void setGuildId(String guildId) {
        beforePropertyWrite("guildId", this.guildId, guildId);
        this.guildId = guildId;
    }

    public String getGuildId() {
        beforePropertyRead("guildId");
        return this.guildId;
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "birthdayChannel":
                return this.birthdayChannel;
            case "guildId":
                return this.guildId;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "birthdayChannel":
                this.birthdayChannel = (String)val;
                break;
            case "guildId":
                this.guildId = (String)val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.birthdayChannel);
        out.writeObject(this.guildId);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.birthdayChannel = (String)in.readObject();
        this.guildId = (String)in.readObject();
    }

}
